services:
  mongo:
    container_name: mongodb
    hostname: mongodb
    env_file: .env
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_ROOT_DATABASE}
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongodb-network

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - mongodb-network
volumes:
  mongodb_data:

networks:
  mongodb-network:
    name: mongodb-network